Fully revised, same functionality

diff --git a/build-ovpn b/build-ovpn
--- a/build-ovpn
+++ b/build-ovpn
@@ -1,8 +1,8 @@
 #!/bin/bash
 #set -vx
-
-## Construct client configuration files
-## $1: name for client (optional, can be set in $name or will be asked)
+## build-ovpn - Make OpenVPN client configuration file
+## Usage: build-ovpn [CLIENT]
+##   CLIENT: clientname (will be asked if not given or set in $UVPN_NAME)
 
 [[ $- == *i* ]] && echo "ABORT: run as script, don't source" && return 1
 ((EUID)) && echo "ABORT: must have root privileges" && exit 2
@@ -10,13 +10,17 @@ self="$(readlink -e "$0")"
 
 source ${self%/*}/vars
 
-! [[ $name ]] && [[ $1 ]] && name=$1
+name=$UVPN_NAME
+: ${name:=$1}
 while [[ ! $name ]] || [[ $name = server || $name = ta || $name = ca ]]
 do
-	read -p "Give proper client name: " name
+	[[ $name ]] && echo "Client name '$name' is unacceptable"
+	read -rp "Give proper client name: " name
 done
 
-! [[ $WAN ]] && echo "ABORT: WAN in vars must be set to external DNS/IP of the server" && exit 3
+[[ -z $WAN ]] &&
+	echo "ABORT: WAN in vars must be set to external DN/IP(s) of the server" &&
+	exit 3
 REMOTE=
 for wan in $WAN
 do
@@ -24,16 +28,19 @@ do
   REMOTE+="remote $url $port"$'\n'
 done
 
-[[ $DHCP_RANGE ]] && {
-	getroute=$(ip route get 8.8.8.8)
-	[[ $GW ]] || read _ _ GW _ <<<"$getroute"
-	[[ $MASK ]] || {
-		[[ $DEV ]] || read _ _ _ _ DEV _ <<<"$getroute"
+if [[ $DHCP_RANGE ]]
+then
+	getroute=($(ip route get 8.8.8.8))
+	: ${GW:=${getroute[2]}}
+	if [[ -z $MASK ]]
+	then
+		: ${DEV:=${getroute[4]}}
 		MASK=$(ifconfig $DEV |sed 's/^.*Mask://' |grep '^[0-9.]*.$')
-	}
+	fi
 	start=${DHCP_RANGE%-*} end=${DHCP_RANGE#*-}
 	bridge="server-bridge $GW $MASK ${GW%.*}.$start ${GW%.*}.$end"
-}
+fi
+
 ovpn="$KEY_DIR/$name.ovpn"
 cafile="$KEY_DIR/ca.crt"
 tafile="$KEY_DIR/ta.key"
@@ -48,36 +55,37 @@ crt=$(sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' "$crtfile")
 key=$(cat "$keyfile")
 [[ -z $crt || -z $key ]] && echo "ABORT: certificate or key not generated" && exit 5
 
-echo "client
-dev tun
-proto udp
-${REMOTE}resolv-retry infinite
-nobind
-persist-key
-persist-tun
-$bridge
-remote-cert-tls server
-; tls-version-min 1.2
-key-direction 1
-verify-x509-name $KEY_NAME name
-cipher AES-256-CBC
-auth SHA256
-comp-lzo
-verb 4
-<ca>
-$ca
-</ca>
-<cert>
-$crt
-</cert>
-<key>
-$key
-</key>
-<tls-auth>
-$ta
-</tls-auth>
-" >"$ovpn"
+cat <<-EOF >"$ovpn"
+	client
+	dev tun
+	proto udp
+	${REMOTE}resolv-retry infinite
+	nobind
+	persist-key
+	persist-tun
+	$bridge
+	remote-cert-tls server
+	; tls-version-min 1.2
+	key-direction 1
+	verify-x509-name $KEY_NAME name
+	cipher AES-256-CBC
+	auth SHA256
+	comp-lzo
+	verb 4
+	<ca>
+	$ca
+	</ca>
+	<cert>
+	$crt
+	</cert>
+	<key>
+	$key
+	</key>
+	<tls-auth>
+	$ta
+	</tls-auth>
+EOF
 
-echo "Done building $ovpn"
+echo "Client configuration file '$ovpn' done"
 
 exit 0
diff --git a/build-server b/build-server
--- a/build-server
+++ b/build-server
@@ -1,30 +1,37 @@
 #!/bin/bash
 #set -vx
-
-## Install and setup OpenVPN server
-## $1: clean (optional: all old keys and certificates will be wiped)
+## build-server - Install and setup OpenVPN server
+## Usage: build-server [clean]
+##   clean: all old keys and certificates will be wiped
 
 [[ $- == *i* ]] && echo "ABORT: run as script, don't source" && return 1
 ((EUID)) && echo "ABORT: must have root privileges" && exit 2
-self="$(readlink -e "$0")"
+self=$(readlink -e "$0") dir=${self%/*}
+
+StopOpenVPN(){ ## Stop server in case it's running
+	echo "Stopping OpenVPN server if it's running"
+	[[ -x /bin/systemctl ]] && systemctl stop openvpn@server ||
+		service openvpn stop
+}
 
 ## Required packages
 apt install openvpn easy-rsa
 ## Fix bug in pkitool
-sed -i 's/KEY_ALTNAMES="$KEY_CN"/KEY_ALTNAMES="DNS:$KEY_CN"/g' /usr/share/easy-rsa/pkitool
+sed -i 's/KEY_ALTNAMES="$KEY_CN"/KEY_ALTNAMES="DNS:$KEY_CN"/g' \
+		/usr/share/easy-rsa/pkitool
 
 ## Set variables
-source ${self%/*}/vars
-getroute=$(ip route get 8.8.8.8)
-[[ $DEV ]] || read _ _ _ _ DEV _ <<<"$getroute"
-[[ $GW ]] || read _ _ GW _ <<<"$getroute"
-[[ $LANIP ]] || read _ _ _ _ _ _ LANIP _ <<<"$getroute"
+source "$dir/vars"
+[[ $LANPORT ]] || LANPORT=1194
+getroute=($(ip route get 8.8.8.8))
+[[ $DEV ]] || DEV=${getroute[4]}
+[[ $GW ]] || GW=${getroute[2]}
+[[ $LANIP ]] || LANIP==${getroute[6]}
 [[ $MASK ]] || MASK=$(ifconfig $DEV |sed 's/^.*Mask://' |grep '^[0-9.]*.$')
-IFS=. read -r i1 i2 i3 i4 <<<$LANIP
-IFS=. read -r m1 m2 m3 m4 <<<$MASK
-net="$(echo "$((i1&m1)).$((i2&m2)).$((i3&m3)).$((i4&m4))")"
+IFS=. read -r i1 i2 i3 i4 <<<"$LANIP"
+IFS=. read -r m1 m2 m3 m4 <<<"$MASK"
+net=$((i1&m1)).$((i2&m2)).$((i3&m3)).$((i4&m4))
 echo "Using device $DEV with IP $LANIP mask $MASK through $GW"
-read -p "Continuing with these settings, Ctrl-C to abort, Enter if OK "
 
 index="$KEY_DIR/index.txt"
 serial="$KEY_DIR/serial"
@@ -43,11 +50,14 @@ lcrt="$CONF/${crt##*/}"
 lkey="$CONF/${key##*/}"
 
 ## Check for non-links in $CONF
-[[ -a "$lca"  && ! -L "$ldh" ]] && echo "ABORT: $ldh no link" && exit 3
-[[ -a "$lca"  && ! -L "$lta" ]] && echo "ABORT: $lta no link" && exit 4
-[[ -a "$lca"  && ! -L "$lca" ]] && echo "ABORT: $lca no link" && exit 5
-[[ -a "$lca"  && ! -L "$lcrt" ]] && echo "ABORT: $lcrt no link" && exit 6
-[[ -a "$lca"  && ! -L "$lkey" ]] && echo "ABORT: $lkey no link" && exit 7
+if [[ -a "$lca" ]]
+then
+	[[ ! -L "$ldh" ]] && echo "ABORT: $ldh no link" && exit 3
+	[[ ! -L "$lta" ]] && echo "ABORT: $lta no link" && exit 4
+	[[ ! -L "$lca" ]] && echo "ABORT: $lca no link" && exit 5
+	[[ ! -L "$lcrt" ]] && echo "ABORT: $lcrt no link" && exit 6
+	[[ ! -L "$lkey" ]] && echo "ABORT: $lkey no link" && exit 7
+fi
 
 DHCP=
 for dhcp in $DNS
@@ -56,44 +66,43 @@ do
 	[[ $dhcp ]] && DHCP+="push \"dhcp-option DNS $dhcp\""$'\n'
 done
 
-config="dev tun
-proto udp
-port $LANPORT
-ca \"$ca\"
-cert \"$crt\"
-key \"$key\"
-dh \"$dh\"
-## server and client tun net
-server 10.8.0.0 255.255.255.0
-ifconfig 10.8.0.1 10.8.0.2
-push \"route 10.8.0.1 255.255.255.255\"
-push \"route 10.8.0.0 255.255.255.0\"
-push \"route $net $MASK\"
-${DHCP}push \"redirect-gateway def1\"
-client-to-client
-duplicate-cn
-keepalive 10 120
-tls-version-min 1.2
-tls-auth \"$ta\" 0
-cipher AES-256-CBC
-auth SHA256
-comp-lzo
-user nobody
-group nogroup
-persist-key
-persist-tun
-; crl-verify \"$CONF/crl.pem\"
-status \"$CONF/status.log\" 20
-log \"$CONF/openvpn.log\"
-verb 4
-"
-
-## Stop server in case it's running
-[[ -x /bin/systemctl ]] && systemctl stop openvpn@server || service openvpn stop
+read -rd '' config <<-EOF
+	dev tun
+	proto udp
+	port $LANPORT
+	ca "$ca"
+	cert "$crt"
+	key "$key"
+	dh "$dh"
+	## server and client tun net
+	server 10.8.0.0 255.255.255.0
+	ifconfig 10.8.0.1 10.8.0.2
+	push "route 10.8.0.1 255.255.255.255"
+	push "route 10.8.0.0 255.255.255.0"
+	push "route $net $MASK"
+	${DHCP}push "redirect-gateway def1"
+	client-to-client
+	duplicate-cn
+	keepalive 10 120
+	tls-version-min 1.2
+	tls-auth "$ta" 0
+	cipher AES-256-CBC
+	auth SHA256
+	comp-lzo
+	user nobody
+	group nogroup
+	persist-key
+	persist-tun
+	; crl-verify "$CONF/crl.pem"
+	status "$CONF/status.log" 20
+	log "$CONF/openvpn.log"
+	verb 4
+EOF
 
 if [[ $1 = clean ]]
 then
 	read -p "Removing directory $KEY_DIR, Ctrl-C to abort, Enter if OK "
+	StopOpenVPN
 	rm -rf "$KEY_DIR"
 	mkdir -p "$KEY_DIR"
 	chmod go-rwx "$KEY_DIR"
@@ -104,37 +113,47 @@ then
 	"$EASY_RSA/pkitool" --initca
 	"$EASY_RSA/pkitool" --server "$KEY_NAME"
 	echo "$config" >"$conf"
-else
-	mkdir -p "$KEY_DIR"
-	chmod go-rwx "$KEY_DIR"
-	! [[ -f "$index" ]] && touch "$index"
-	! [[ -f "$serial" ]] && echo 01 >"$serial"
-	! [[ -f "$dh" ]] && "$OPENSSL" dhparam -out "$dh" "$KEY_SIZE"
-	! [[ -f "$ta" ]] && openvpn --genkey --secret "$ta"
-	! [[ -f "$ca" ]] && "$EASY_RSA/pkitool" --initca
-	! [[ -f "$crt" && -f "$key" ]] && "$EASY_RSA/pkitool" --server "$KEY_NAME"
-	! [[ -f "$conf" ]] && echo "$config" >"$conf"
+	exit 0
 fi
-! ln -sf "$dh" $CONF/ && echo "ABORT: can't create link for $dh in $CONF" && exit 8
-! ln -sf "$ta" $CONF/ && echo "ABORT: can't create link for $ta in $CONF" && exit 9
-! ln -sf "$ca" $CONF/ && echo "ABORT: can't create link for $ca in $CONF" && exit 10
-! ln -sf "$crt" $CONF/ && echo "ABORT: can't create link for $crt in $CONF" && exit 11
-! ln -sf "$key" $CONF/ && echo "ABORT: can't create link for $key in $CONF" && exit 12
+
+read -p "Writing configuration files, Ctrl-C to abort, Enter if OK "
+StopOpenVPN
+mkdir -p "$KEY_DIR"
+chmod go-rwx "$KEY_DIR"
+! [[ -f "$index" ]] && touch "$index"
+! [[ -f "$serial" ]] && echo 01 >"$serial"
+! [[ -f "$dh" ]] && "$OPENSSL" dhparam -out "$dh" "$KEY_SIZE"
+! [[ -f "$ta" ]] && openvpn --genkey --secret "$ta"
+! [[ -f "$ca" ]] && "$EASY_RSA/pkitool" --initca
+! [[ -f "$crt" && -f "$key" ]] && "$EASY_RSA/pkitool" --server "$KEY_NAME"
+! [[ -f "$conf" ]] && echo "$config" >"$conf"
+
+! ln -sf "$dh" $CONF/ &&
+	echo "ABORT: can't create link for $dh in $CONF" && exit 8
+! ln -sf "$ta" $CONF/ &&
+	echo "ABORT: can't create link for $ta in $CONF" && exit 9
+! ln -sf "$ca" $CONF/ &&
+	echo "ABORT: can't create link for $ca in $CONF" && exit 10
+! ln -sf "$crt" $CONF/ &&
+	echo "ABORT: can't create link for $crt in $CONF" && exit 11
+! ln -sf "$key" $CONF/ &&
+	echo "ABORT: can't create link for $key in $CONF" && exit 12
 
 ## Allow for more client certificates
 sed -i 's/unique_subject = yes/unique_subject = no/' "$KEY_DIR/index.txt.attr"
 
-## Set forwarding on the server
+## Set IPv4 forwarding on the server
 sed -i 's/^#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf
 sysctl -p
 
 ## Start server
+read -p "Starting OpenVPN and set to autostart, Ctrl-C to abort, Enter if OK "
 if [[ -x /bin/systemctl ]]
 then
 	systemctl start openvpn@server
 	systemctl enable openvpn@server
 else
-	## Remove incompatible option
+	## Remove incompatible option :-(
 	sed -i 's/^tls-version-min 1.2/; tls-version-min 1.2/' "$conf"
 	service openvpn start
 	update-rc.d openvpn enable
